# Generated by Django 5.0.4 on 2024-04-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_rename_medico_medicos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Especialidade',
        ),
        migrations.RenameModel(
            old_name='Medicos',
            new_name='Medico',
        ),
    ]
